// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package gfxutils.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ja_bufferedimage_crt extends CustomJavaAction<IMendixObject>
{
	private java.lang.Long w;
	private java.lang.Long h;

	public ja_bufferedimage_crt(IContext context, java.lang.Long w, java.lang.Long h)
	{
		super(context);
		this.w = w;
		this.h = h;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		com.mendix.systemwideinterfaces.core.IMendixObject ret=null;
		try{
			gfxutils.support.BufferedImageStorage bufferedImageStorage=gfxutils.support.BufferedImageStorage.getInstance();
			java.lang.String _Id=bufferedImageStorage.createBufferedImage(w.intValue(),h.intValue());
			ret=com.mendix.core.Core.instantiate(
				this.getContext(),
				"GFXUtils.BufferedImage"
			);
			ret.setValue(
				this.getContext(),
				"_Id",
				_Id
			);
			ret.setValue(
				this.getContext(),
				"width",
				w.intValue()
			);
			ret.setValue(
				this.getContext(),
				"height",
				h.intValue()
			);
		}catch(Exception e){
			//too verbose
		}
		return ret;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ja_bufferedimage_crt";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
