// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package gfxutils.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the GFXUtils module
	public static java.util.List<gfxutils.proxies.BufferedImage> ds_bufferedimage(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.List<IMendixObject> objs = Core.execute(context, "GFXUtils.ds_bufferedimage", params);
			java.util.List<gfxutils.proxies.BufferedImage> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<gfxutils.proxies.BufferedImage>();
				for (IMendixObject obj : objs)
					result.add(gfxutils.proxies.BufferedImage.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static gfxutils.proxies.ConfigPerlin ds_configperlin(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "GFXUtils.ds_configperlin", params);
			return result == null ? null : gfxutils.proxies.ConfigPerlin.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_circle(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _x, java.lang.Long _y, java.lang.Long _radius, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _step)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("x", _x);
			params.put("y", _y);
			params.put("radius", _radius);
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("step", _step);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_circle", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_circle_sopt(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _x, java.lang.Long _y, java.lang.Long _radius, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _step)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("x", _x);
			params.put("y", _y);
			params.put("radius", _radius);
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("step", _step);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_circle_sopt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static gfxutils.proxies.BufferedImage ivk_bufferedimage_crt_test(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "GFXUtils.ivk_bufferedimage_crt_test", params);
			return result == null ? null : gfxutils.proxies.BufferedImage.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_drop(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "GFXUtils.ivk_bufferedimage_drop", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_fill(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_fill", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_fill_opt(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_fill_opt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static gfxutils.proxies.Image ivk_bufferedimage_get(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "GFXUtils.ivk_bufferedimage_get", params);
			return result == null ? null : gfxutils.proxies.Image.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_hline(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _x, java.lang.Long _y, java.lang.Long _w, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("x", _x);
			params.put("y", _y);
			params.put("w", _w);
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_hline", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_hline_opt(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _x, java.lang.Long _y, java.lang.Long _w, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("x", _x);
			params.put("y", _y);
			params.put("w", _w);
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_hline_opt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_line(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long __x0, java.lang.Long __y0, java.lang.Long __x1, java.lang.Long __y1, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("_x0", __x0);
			params.put("_y0", __y0);
			params.put("_x1", __x1);
			params.put("_y1", __y1);
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_line", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_line_opt(IContext context, java.lang.Long _x0, java.lang.Long _y0, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _x1, java.lang.Long _y1, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("x0", _x0);
			params.put("y0", _y0);
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("x1", _x1);
			params.put("y1", _y1);
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_line_opt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_opt(IContext context, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _x, java.lang.Long _y, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("x", _x);
			params.put("y", _y);
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_opt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_2(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_2", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_3(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_3", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_4(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_4", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_5(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_5", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_5_opt(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_5_opt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_6(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_6", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_7(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_7", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_8(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_8", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_8_opt(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_8_opt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_rm(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_rm", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_view_refresh_test(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_view_refresh_test", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_view_test(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_view_test", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_vline(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _x, java.lang.Long _y, java.lang.Long _h, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("x", _x);
			params.put("y", _y);
			params.put("h", _h);
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_vline", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_vline_opt(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _x, java.lang.Long _y, java.lang.Long _h, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("x", _x);
			params.put("y", _y);
			params.put("h", _h);
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_vline_opt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_domain_drop(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "GFXUtils.ivk_domain_drop", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_im_mult(IContext context, gfxutils.proxies.im _a, gfxutils.proxies.im _b, gfxutils.proxies.im _ret)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("a", _a == null ? null : _a.getMendixObject());
			params.put("b", _b == null ? null : _b.getMendixObject());
			params.put("ret", _ret == null ? null : _ret.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_im_mult", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_perlin_test_001(IContext context, gfxutils.proxies.ConfigPerlin _obj_configperlin)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_configperlin", _obj_configperlin == null ? null : _obj_configperlin.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_perlin_test_001", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}