// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package gfxutils.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the GFXUtils module
	public static java.util.List<gfxutils.proxies.BufferedImage> ds_bufferedimage(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.List<IMendixObject> objs = Core.execute(context, "GFXUtils.ds_bufferedimage", params);
			java.util.List<gfxutils.proxies.BufferedImage> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<gfxutils.proxies.BufferedImage>();
				for (IMendixObject obj : objs)
					result.add(gfxutils.proxies.BufferedImage.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static gfxutils.proxies.ConfigPerlin ds_configperlin(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "GFXUtils.ds_configperlin", params);
			return result == null ? null : gfxutils.proxies.ConfigPerlin.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static gfxutils.proxies.Data ds_data(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "GFXUtils.ds_data", params);
			return result == null ? null : gfxutils.proxies.Data.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<gfxutils.proxies.Vec1f> ds_noise_gen000_vec1f(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.List<IMendixObject> objs = Core.execute(context, "GFXUtils.ds_noise_gen000_vec1f", params);
			java.util.List<gfxutils.proxies.Vec1f> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<gfxutils.proxies.Vec1f>();
				for (IMendixObject obj : objs)
					result.add(gfxutils.proxies.Vec1f.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<gfxutils.proxies.Vec1i> ds_noise_gen000_vec1i(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.List<IMendixObject> objs = Core.execute(context, "GFXUtils.ds_noise_gen000_vec1i", params);
			java.util.List<gfxutils.proxies.Vec1i> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<gfxutils.proxies.Vec1i>();
				for (IMendixObject obj : objs)
					result.add(gfxutils.proxies.Vec1i.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.Double ds_perlin_fade(IContext context, java.lang.Double _t)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("t", _t);
			return (java.lang.Double)Core.execute(context, "GFXUtils.ds_perlin_fade", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.Double ds_perlin_grad(IContext context, java.lang.Long _hash, java.lang.Double _x, java.lang.Double _y, java.lang.Double _z)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("hash", _hash);
			params.put("x", _x);
			params.put("y", _y);
			params.put("z", _z);
			return (java.lang.Double)Core.execute(context, "GFXUtils.ds_perlin_grad", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.Double ds_perlin_lerp(IContext context, java.lang.Double _t, java.lang.Double _a, java.lang.Double _b)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("t", _t);
			params.put("a", _a);
			params.put("b", _b);
			return (java.lang.Double)Core.execute(context, "GFXUtils.ds_perlin_lerp", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.Long ds_perlin_lut(IContext context, java.lang.Long _i)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("i", _i);
			return (java.lang.Long)Core.execute(context, "GFXUtils.ds_perlin_lut", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.Double ds_perlin_noise(IContext context, java.lang.Double __x, java.lang.Double __y, java.lang.Double __z)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("_x", __x);
			params.put("_y", __y);
			params.put("_z", __z);
			return (java.lang.Double)Core.execute(context, "GFXUtils.ds_perlin_noise", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static gfxutils.proxies.Vec1f ds_vec1f(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "GFXUtils.ds_vec1f", params);
			return result == null ? null : gfxutils.proxies.Vec1f.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static gfxutils.proxies.Vec1i ds_vec1i(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "GFXUtils.ds_vec1i", params);
			return result == null ? null : gfxutils.proxies.Vec1i.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static gfxutils.proxies.Vec1s ds_vec1s(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "GFXUtils.ds_vec1s", params);
			return result == null ? null : gfxutils.proxies.Vec1s.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static gfxutils.proxies.Vec2f ds_vec2f(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "GFXUtils.ds_vec2f", params);
			return result == null ? null : gfxutils.proxies.Vec2f.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static gfxutils.proxies.Vec2i ds_vec2i(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "GFXUtils.ds_vec2i", params);
			return result == null ? null : gfxutils.proxies.Vec2i.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ds_vec2s(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "GFXUtils.ds_vec2s", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static gfxutils.proxies.Vec3f ds_vec3f(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "GFXUtils.ds_vec3f", params);
			return result == null ? null : gfxutils.proxies.Vec3f.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static gfxutils.proxies.Vec3i ds_vec3i(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "GFXUtils.ds_vec3i", params);
			return result == null ? null : gfxutils.proxies.Vec3i.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static gfxutils.proxies.Vec3s ds_vec3s(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "GFXUtils.ds_vec3s", params);
			return result == null ? null : gfxutils.proxies.Vec3s.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static gfxutils.proxies.Vec4f ds_vec4f(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "GFXUtils.ds_vec4f", params);
			return result == null ? null : gfxutils.proxies.Vec4f.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static gfxutils.proxies.Vec4i ds_vec4i(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "GFXUtils.ds_vec4i", params);
			return result == null ? null : gfxutils.proxies.Vec4i.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static gfxutils.proxies.Vec4s ds_vec4s(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "GFXUtils.ds_vec4s", params);
			return result == null ? null : gfxutils.proxies.Vec4s.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void hsv2rgb(IContext context, gfxutils.proxies.Rgb _obj_rgb, gfxutils.proxies.Hsv _obj_hsv)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_rgb", _obj_rgb == null ? null : _obj_rgb.getMendixObject());
			params.put("obj_hsv", _obj_hsv == null ? null : _obj_hsv.getMendixObject());
			Core.execute(context, "GFXUtils.hsv2rgb", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_circle(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _x, java.lang.Long _y, java.lang.Long _radius, java.lang.Long _r, java.lang.Long _g, java.lang.Long _step, java.lang.Long _b, java.lang.Long _a)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("x", _x);
			params.put("y", _y);
			params.put("radius", _radius);
			params.put("r", _r);
			params.put("g", _g);
			params.put("step", _step);
			params.put("b", _b);
			params.put("a", _a);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_circle", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_circle_alpha(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _x, java.lang.Long _y, java.lang.Long _radius, java.lang.Long _r, java.lang.Long _g, java.lang.Long _step, java.lang.Long _b, java.lang.Long _a)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("x", _x);
			params.put("y", _y);
			params.put("radius", _radius);
			params.put("r", _r);
			params.put("g", _g);
			params.put("step", _step);
			params.put("b", _b);
			params.put("a", _a);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_circle_alpha", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_circle_sopt(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _x, java.lang.Long _y, java.lang.Long _radius, java.lang.Long _r, java.lang.Long _g, java.lang.Long _step, java.lang.Long _b, java.lang.Long _a)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("x", _x);
			params.put("y", _y);
			params.put("radius", _radius);
			params.put("r", _r);
			params.put("g", _g);
			params.put("step", _step);
			params.put("b", _b);
			params.put("a", _a);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_circle_sopt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static gfxutils.proxies.BufferedImage ivk_bufferedimage_crt_test(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "GFXUtils.ivk_bufferedimage_crt_test", params);
			return result == null ? null : gfxutils.proxies.BufferedImage.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_drop(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "GFXUtils.ivk_bufferedimage_drop", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_fill(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _a)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("a", _a);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_fill", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_fill_opt(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _a)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("a", _a);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_fill_opt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_fill_opt_alpha(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _a)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("a", _a);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_fill_opt_alpha", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static gfxutils.proxies.Image ivk_bufferedimage_get(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "GFXUtils.ivk_bufferedimage_get", params);
			return result == null ? null : gfxutils.proxies.Image.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_hline(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _x, java.lang.Long _y, java.lang.Long _w, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _a)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("x", _x);
			params.put("y", _y);
			params.put("w", _w);
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("a", _a);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_hline", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_hline_alpha(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _x, java.lang.Long _y, java.lang.Long _w, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _a)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("x", _x);
			params.put("y", _y);
			params.put("w", _w);
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("a", _a);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_hline_alpha", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_hline_opt(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _x, java.lang.Long _y, java.lang.Long _h, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _a)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("x", _x);
			params.put("y", _y);
			params.put("h", _h);
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("a", _a);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_hline_opt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_line(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long __x0, java.lang.Long __y0, java.lang.Long __x1, java.lang.Long __y1, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _a)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("_x0", __x0);
			params.put("_y0", __y0);
			params.put("_x1", __x1);
			params.put("_y1", __y1);
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("a", _a);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_line", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_line_alpha(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long __x0, java.lang.Long __y0, java.lang.Long __x1, java.lang.Long __y1, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _a)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("_x0", __x0);
			params.put("_y0", __y0);
			params.put("_x1", __x1);
			params.put("_y1", __y1);
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("a", _a);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_line_alpha", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_line_opt(IContext context, java.lang.Long _x0, java.lang.Long _y0, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _x1, java.lang.Long _y1, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _a)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("x0", _x0);
			params.put("y0", _y0);
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("x1", _x1);
			params.put("y1", _y1);
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("a", _a);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_line_opt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_perlin(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _a)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("a", _a);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_perlin", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_opt(IContext context, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _x, java.lang.Long _y, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _a)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("x", _x);
			params.put("y", _y);
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("a", _a);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_opt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_10(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_10", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_11(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_11", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_12(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_12", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_13(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_13", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_2(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_2", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_3(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_3", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_4(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_4", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_5(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_5", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_5_alpha(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_5_alpha", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_5_opt(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_5_opt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_6(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_6", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_6_opt(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_6_opt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_7(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_7", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_7_alpha(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_7_alpha", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_8(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_8", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_8_alpha(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_8_alpha", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_8_opt(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_8_opt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_9_alpha(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_9_alpha", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_putpixel_test_9_opt(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_putpixel_test_9_opt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_rect(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _a, java.lang.Long __x0, java.lang.Long __y0, java.lang.Long __x1, java.lang.Long __y1)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("a", _a);
			params.put("_x0", __x0);
			params.put("_y0", __y0);
			params.put("_x1", __x1);
			params.put("_y1", __y1);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_rect", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_rect_filled(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _a, java.lang.Long __x0, java.lang.Long __y0, java.lang.Long __x1, java.lang.Long __y1)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("a", _a);
			params.put("_x0", __x0);
			params.put("_y0", __y0);
			params.put("_x1", __x1);
			params.put("_y1", __y1);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_rect_filled", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_rm(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_rm", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_simplex(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _a)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("a", _a);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_simplex", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_view_refresh_test(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_view_refresh_test", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_view_test(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_bufferedimage_view_test", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_vline(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _x, java.lang.Long _y, java.lang.Long _h, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _a)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("x", _x);
			params.put("y", _y);
			params.put("h", _h);
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("a", _a);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_vline", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_vline_alpha(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _x, java.lang.Long _y, java.lang.Long _h, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _a)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("x", _x);
			params.put("y", _y);
			params.put("h", _h);
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("a", _a);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_vline_alpha", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_bufferedimage_vline_opt(IContext context, gfxutils.proxies.BufferedImage _obj_bufferedimage, java.lang.Long _x, java.lang.Long _y, java.lang.Long _w, java.lang.Long _r, java.lang.Long _g, java.lang.Long _b, java.lang.Long _a)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_bufferedimage", _obj_bufferedimage == null ? null : _obj_bufferedimage.getMendixObject());
			params.put("x", _x);
			params.put("y", _y);
			params.put("w", _w);
			params.put("r", _r);
			params.put("g", _g);
			params.put("b", _b);
			params.put("a", _a);
			Core.execute(context, "GFXUtils.ivk_bufferedimage_vline_opt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_domain_drop(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "GFXUtils.ivk_domain_drop", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_im_mult(IContext context, gfxutils.proxies.im _a, gfxutils.proxies.im _b, gfxutils.proxies.im _ret)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("a", _a == null ? null : _a.getMendixObject());
			params.put("b", _b == null ? null : _b.getMendixObject());
			params.put("ret", _ret == null ? null : _ret.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_im_mult", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_mf_test(IContext context, gfxutils.proxies.Vec1s _obj_vec1s)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_vec1s", _obj_vec1s == null ? null : _obj_vec1s.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_mf_test", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void ivk_perlin_test_001(IContext context, gfxutils.proxies.ConfigPerlin _obj_configperlin)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_configperlin", _obj_configperlin == null ? null : _obj_configperlin.getMendixObject());
			Core.execute(context, "GFXUtils.ivk_perlin_test_001", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void rgb2hsv(IContext context, gfxutils.proxies.Rgb _obj_rgb, gfxutils.proxies.Hsv _obj_hsv)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("obj_rgb", _obj_rgb == null ? null : _obj_rgb.getMendixObject());
			params.put("obj_hsv", _obj_hsv == null ? null : _obj_hsv.getMendixObject());
			Core.execute(context, "GFXUtils.rgb2hsv", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}