// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package gfxutils.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * &
 */
public class ja_and extends CustomJavaAction<java.lang.Long>
{
	private java.lang.Long a;
	private java.lang.Long b;

	public ja_and(IContext context, java.lang.Long a, java.lang.Long b)
	{
		super(context);
		this.a = a;
		this.b = b;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		return a&b;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ja_and";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
