// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package gfxutils.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ja_bufferedimage_rm extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __obj_bufferedimage;
	private gfxutils.proxies.BufferedImage obj_bufferedimage;

	public ja_bufferedimage_rm(IContext context, IMendixObject obj_bufferedimage)
	{
		super(context);
		this.__obj_bufferedimage = obj_bufferedimage;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.obj_bufferedimage = __obj_bufferedimage == null ? null : gfxutils.proxies.BufferedImage.initialize(getContext(), __obj_bufferedimage);

		// BEGIN USER CODE
		java.lang.Boolean ret=false;
		try{
			if(obj_bufferedimage!=null){
				java.lang.String _id=
				obj_bufferedimage.getMendixObject().getValue(
					this.getContext(),
					"_Id"
				);
				if(_id!=null){
					gfxutils.support.BufferedImageStorage.getInstance().removeBufferedImage(_id);
				}else{
					com.mendix.core.Core.getLogger(this.toString()).error("_Id NULL:Aborting");
				}
			}else{
				com.mendix.core.Core.getLogger(this.toString()).error("obj_bufferedimage NULL:Aborting");
			}
		}catch(Exception e){
			//verbosity!!!
		}
                return ret;
      
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ja_bufferedimage_rm";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
