// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package gfxutils.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ja_bufferedimage_lst extends CustomJavaAction<java.util.List<IMendixObject>>
{
	public ja_bufferedimage_lst(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> ret=null;
		try{
			java.util.HashMap<java.lang.String,java.awt.image.BufferedImage> bufferedImages=gfxutils.support.BufferedImageStorage.getInstance().getBufferedImages();
			ret=new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixObject>();
			for (java.util.Map.Entry<java.lang.String,java.awt.image.BufferedImage> entry:bufferedImages.entrySet()){
				com.mendix.systemwideinterfaces.core.IMendixObject o=com.mendix.core.Core.instantiate(
					this.getContext(),
					"GFXUtils.BufferedImage"
				);
				o.setValue(
					this.getContext(),
					"_Id",
					entry.getKey()
				);
				o.setValue(
					this.getContext(),
					"width",
					entry.getValue().getWidth()
				);
				o.setValue(
					this.getContext(),
					"height",
					entry.getValue().getHeight()
				);
				ret.add(o);
			}
		}catch(Exception e){
			//verbosity!!
		}
		return ret;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ja_bufferedimage_lst";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
