// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package gfxutils.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * invokes microflow
 */
public class ja_ivk extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String mf;

	public ja_ivk(IContext context, java.lang.String mf)
	{
		super(context);
		this.mf = mf;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		java.util.Map<java.lang.String, java.lang.Object> params=new java.util.LinkedHashMap<java.lang.String,java.lang.Object>();
		com.mendix.core.Core.execute(this.getContext(),mf,params);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ja_ivk";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
