// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package gfxutils.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * description:
 *     populates arrnam (if found) with generated list of objnam
 * parameters:
 *     objnam:
 *          MODULE.ENTITY
 *     arrnam:
 *         exact name LIST of type MODULE.ENTITY existing before call
 *     sz:
 *        amount of MODULE.ENTITY to instantiate and put in arrnam
 */
public class ja_orm_genarr extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String objnam;
	private java.lang.String arrnam;
	private java.lang.Long sz;

	public ja_orm_genarr(IContext context, java.lang.String objnam, java.lang.String arrnam, java.lang.Long sz)
	{
		super(context);
		this.objnam = objnam;
		this.arrnam = arrnam;
		this.sz = sz;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ja_orm_genarr";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
