// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package gfxutils.proxies;

public class ConfigPerlin
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject configPerlinMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GFXUtils.ConfigPerlin";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Width("Width"),
		Height("Height"),
		Scale("Scale"),
		ConfigPerlin_Image("GFXUtils.ConfigPerlin_Image");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ConfigPerlin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "GFXUtils.ConfigPerlin"));
	}

	protected ConfigPerlin(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject configPerlinMendixObject)
	{
		if (configPerlinMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("GFXUtils.ConfigPerlin", configPerlinMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a GFXUtils.ConfigPerlin");

		this.configPerlinMendixObject = configPerlinMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ConfigPerlin.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static gfxutils.proxies.ConfigPerlin initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return gfxutils.proxies.ConfigPerlin.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static gfxutils.proxies.ConfigPerlin initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new gfxutils.proxies.ConfigPerlin(context, mendixObject);
	}

	public static gfxutils.proxies.ConfigPerlin load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return gfxutils.proxies.ConfigPerlin.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Width
	 */
	public final java.lang.Integer getWidth()
	{
		return getWidth(getContext());
	}

	/**
	 * @param context
	 * @return value of Width
	 */
	public final java.lang.Integer getWidth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Width.toString());
	}

	/**
	 * Set value of Width
	 * @param width
	 */
	public final void setWidth(java.lang.Integer width)
	{
		setWidth(getContext(), width);
	}

	/**
	 * Set value of Width
	 * @param context
	 * @param width
	 */
	public final void setWidth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer width)
	{
		getMendixObject().setValue(context, MemberNames.Width.toString(), width);
	}

	/**
	 * @return value of Height
	 */
	public final java.lang.Integer getHeight()
	{
		return getHeight(getContext());
	}

	/**
	 * @param context
	 * @return value of Height
	 */
	public final java.lang.Integer getHeight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Height.toString());
	}

	/**
	 * Set value of Height
	 * @param height
	 */
	public final void setHeight(java.lang.Integer height)
	{
		setHeight(getContext(), height);
	}

	/**
	 * Set value of Height
	 * @param context
	 * @param height
	 */
	public final void setHeight(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer height)
	{
		getMendixObject().setValue(context, MemberNames.Height.toString(), height);
	}

	/**
	 * @return value of Scale
	 */
	public final java.lang.Double getScale()
	{
		return getScale(getContext());
	}

	/**
	 * @param context
	 * @return value of Scale
	 */
	public final java.lang.Double getScale(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Double) getMendixObject().getValue(context, MemberNames.Scale.toString());
	}

	/**
	 * Set value of Scale
	 * @param scale
	 */
	public final void setScale(java.lang.Double scale)
	{
		setScale(getContext(), scale);
	}

	/**
	 * Set value of Scale
	 * @param context
	 * @param scale
	 */
	public final void setScale(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Double scale)
	{
		getMendixObject().setValue(context, MemberNames.Scale.toString(), scale);
	}

	/**
	 * @return value of ConfigPerlin_Image
	 */
	public final gfxutils.proxies.Image getConfigPerlin_Image() throws com.mendix.core.CoreException
	{
		return getConfigPerlin_Image(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfigPerlin_Image
	 */
	public final gfxutils.proxies.Image getConfigPerlin_Image(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		gfxutils.proxies.Image result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ConfigPerlin_Image.toString());
		if (identifier != null)
			result = gfxutils.proxies.Image.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ConfigPerlin_Image
	 * @param configperlin_image
	 */
	public final void setConfigPerlin_Image(gfxutils.proxies.Image configperlin_image)
	{
		setConfigPerlin_Image(getContext(), configperlin_image);
	}

	/**
	 * Set value of ConfigPerlin_Image
	 * @param context
	 * @param configperlin_image
	 */
	public final void setConfigPerlin_Image(com.mendix.systemwideinterfaces.core.IContext context, gfxutils.proxies.Image configperlin_image)
	{
		if (configperlin_image == null)
			getMendixObject().setValue(context, MemberNames.ConfigPerlin_Image.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ConfigPerlin_Image.toString(), configperlin_image.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return configPerlinMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final gfxutils.proxies.ConfigPerlin that = (gfxutils.proxies.ConfigPerlin) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "GFXUtils.ConfigPerlin";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
