// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package gfxutils.proxies;

public class Data
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GFXUtils.Data";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_a1("GFXUtils._a1"),
		_a2("GFXUtils._a2");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Data(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "GFXUtils.Data"));
	}

	protected Data(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dataMendixObject)
	{
		if (dataMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("GFXUtils.Data", dataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a GFXUtils.Data");

		this.dataMendixObject = dataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Data.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static gfxutils.proxies.Data initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return gfxutils.proxies.Data.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static gfxutils.proxies.Data initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("GFXUtils.Vec1f", mendixObject.getType()))
			return gfxutils.proxies.Vec1f.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("GFXUtils.Vec1i", mendixObject.getType()))
			return gfxutils.proxies.Vec1i.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("GFXUtils.Vec1s", mendixObject.getType()))
			return gfxutils.proxies.Vec1s.initialize(context, mendixObject);

		return new gfxutils.proxies.Data(context, mendixObject);
	}

	public static gfxutils.proxies.Data load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return gfxutils.proxies.Data.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _a1
	 */
	public final gfxutils.proxies.Data get_a1() throws com.mendix.core.CoreException
	{
		return get_a1(getContext());
	}

	/**
	 * @param context
	 * @return value of _a1
	 */
	public final gfxutils.proxies.Data get_a1(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		gfxutils.proxies.Data result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames._a1.toString());
		if (identifier != null)
			result = gfxutils.proxies.Data.load(context, identifier);
		return result;
	}

	/**
	 * Set value of _a1
	 * @param _a1
	 */
	public final void set_a1(gfxutils.proxies.Data _a1)
	{
		set_a1(getContext(), _a1);
	}

	/**
	 * Set value of _a1
	 * @param context
	 * @param _a1
	 */
	public final void set_a1(com.mendix.systemwideinterfaces.core.IContext context, gfxutils.proxies.Data _a1)
	{
		if (_a1 == null)
			getMendixObject().setValue(context, MemberNames._a1.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames._a1.toString(), _a1.getMendixObject().getId());
	}

	/**
	 * @return value of _a2
	 */
	public final java.util.List<gfxutils.proxies.Data> get_a2() throws com.mendix.core.CoreException
	{
		return get_a2(getContext());
	}

	/**
	 * @param context
	 * @return value of _a2
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<gfxutils.proxies.Data> get_a2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<gfxutils.proxies.Data> result = new java.util.ArrayList<gfxutils.proxies.Data>();
		Object valueObject = getMendixObject().getValue(context, MemberNames._a2.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(gfxutils.proxies.Data.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of _a2
	 * @param _a2
	 */
	public final void set_a2(java.util.List<gfxutils.proxies.Data> _a2)
	{
		set_a2(getContext(), _a2);
	}

	/**
	 * Set value of _a2
	 * @param context
	 * @param _a2
	 */
	public final void set_a2(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<gfxutils.proxies.Data> _a2)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (gfxutils.proxies.Data proxyObject : _a2)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames._a2.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final gfxutils.proxies.Data that = (gfxutils.proxies.Data) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "GFXUtils.Data";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
