// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package gfxutils.proxies;

public class Hsv
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject hsvMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GFXUtils.Hsv";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		h("h"),
		s("s"),
		v("v");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Hsv(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "GFXUtils.Hsv"));
	}

	protected Hsv(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject hsvMendixObject)
	{
		if (hsvMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("GFXUtils.Hsv", hsvMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a GFXUtils.Hsv");

		this.hsvMendixObject = hsvMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Hsv.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static gfxutils.proxies.Hsv initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return gfxutils.proxies.Hsv.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static gfxutils.proxies.Hsv initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new gfxutils.proxies.Hsv(context, mendixObject);
	}

	public static gfxutils.proxies.Hsv load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return gfxutils.proxies.Hsv.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of h
	 */
	public final java.lang.Double geth()
	{
		return geth(getContext());
	}

	/**
	 * @param context
	 * @return value of h
	 */
	public final java.lang.Double geth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Double) getMendixObject().getValue(context, MemberNames.h.toString());
	}

	/**
	 * Set value of h
	 * @param h
	 */
	public final void seth(java.lang.Double h)
	{
		seth(getContext(), h);
	}

	/**
	 * Set value of h
	 * @param context
	 * @param h
	 */
	public final void seth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Double h)
	{
		getMendixObject().setValue(context, MemberNames.h.toString(), h);
	}

	/**
	 * @return value of s
	 */
	public final java.lang.Double gets()
	{
		return gets(getContext());
	}

	/**
	 * @param context
	 * @return value of s
	 */
	public final java.lang.Double gets(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Double) getMendixObject().getValue(context, MemberNames.s.toString());
	}

	/**
	 * Set value of s
	 * @param s
	 */
	public final void sets(java.lang.Double s)
	{
		sets(getContext(), s);
	}

	/**
	 * Set value of s
	 * @param context
	 * @param s
	 */
	public final void sets(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Double s)
	{
		getMendixObject().setValue(context, MemberNames.s.toString(), s);
	}

	/**
	 * @return value of v
	 */
	public final java.lang.Double getv()
	{
		return getv(getContext());
	}

	/**
	 * @param context
	 * @return value of v
	 */
	public final java.lang.Double getv(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Double) getMendixObject().getValue(context, MemberNames.v.toString());
	}

	/**
	 * Set value of v
	 * @param v
	 */
	public final void setv(java.lang.Double v)
	{
		setv(getContext(), v);
	}

	/**
	 * Set value of v
	 * @param context
	 * @param v
	 */
	public final void setv(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Double v)
	{
		getMendixObject().setValue(context, MemberNames.v.toString(), v);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return hsvMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final gfxutils.proxies.Hsv that = (gfxutils.proxies.Hsv) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "GFXUtils.Hsv";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
