// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package gfxutils.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ja_bufferedimage_get extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __obj_bufferedimage;
	private gfxutils.proxies.BufferedImage obj_bufferedimage;
	private IMendixObject __obj_filedocument;
	private system.proxies.FileDocument obj_filedocument;

	public ja_bufferedimage_get(IContext context, IMendixObject obj_bufferedimage, IMendixObject obj_filedocument)
	{
		super(context);
		this.__obj_bufferedimage = obj_bufferedimage;
		this.__obj_filedocument = obj_filedocument;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.obj_bufferedimage = __obj_bufferedimage == null ? null : gfxutils.proxies.BufferedImage.initialize(getContext(), __obj_bufferedimage);

		this.obj_filedocument = __obj_filedocument == null ? null : system.proxies.FileDocument.initialize(getContext(), __obj_filedocument);

		// BEGIN USER CODE
		java.lang.Boolean ret=false;
		if(obj_bufferedimage!=null){
			if(obj_filedocument!=null){
				if(obj_bufferedimage.getMendixObject().getValue(this.getContext(),"_Id")!=null){
					java.awt.image.BufferedImage bi=gfxutils.support.BufferedImageStorage.getInstance().getBufferedImage(obj_bufferedimage.getMendixObject().getValue(this.getContext(),"_Id"));
					if(bi!=null){
                                                java.io.ByteArrayOutputStream bos = new java.io.ByteArrayOutputStream();
                                                byte[] barr = bos.toByteArray();
                                                javax.imageio.ImageIO.write(bi,"png",bos);
                                                java.io.ByteArrayInputStream is = new java.io.ByteArrayInputStream(bos.toByteArray());
                                                com.mendix.core.Core.storeFileDocumentContent(this.getContext(),obj_filedocument.getMendixObject(),obj_filedocument.getMendixObject().getValue(this.getContext(),"Name"),is);
                                                com.mendix.core.Core.commit(this.getContext(),obj_filedocument.getMendixObject());
                                                ret=true;
					}else{
						//com.mendix.core.Core.getLogger(this.toString()).error("no buffered image found for given id: Aborting...");//verbosity!!!
					}
				}else{
					//com.mendix.core.Core.getLogger(this.toString()).error("obj_bufferedimage._Id NULL:Aborting...");//verbosity!!!
				}
			}else{
				//com.mendix.core.Core.getLogger(this.toString()).error("obj_filedocument NULL:Aborting...");//verbosity!!!
			}
		}else{
			//com.mendix.core.Core.getLogger(this.toString()).error("obj_bufferedimage NULL:Aborting...");//verbosity!!!
		}
		return ret;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ja_bufferedimage_get";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
